<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('index') ?>">Middle Front</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav pull-right">
                <li><a href="<?php echo $this->url('index') ?>"><?php echo $this->translate('Home') ?></a></li>

                <li>
                    <?php if(!$this->userIdentity()->isLogged()){?>
                        <a href="<?php
                        echo $this->url('auc/auc_child', array('action' => 'login'),
                            array('query' => array('rt' => $this->ServerUrl(true)))) ?>">
                            <?php echo $this->translate('Login')
                            ?>
                        </a>
                    <?php }?>

                    <?php if($this->userIdentity()->isLogged()){?>
                        <a href="<?php
                        echo $this->url('auc/auc_child', array('action' => 'logout'),
                            array('query' => array('rt' => $this->ServerUrl(true)))) ?>">
                            <?php echo $this->translate('Logout')
                            ?>
                        </a>
                    <?php }?>
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>