<?php
echo $this->headLink( /*array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')*/)
    ->appendStylesheet($this->basePath() . '/st/tmln/css/style.css')
?>

<div class="wall_cover container">
<div id="wall" class="userWall">
<?php if($this->isOwner) echo $this->partial("timeline/post_form")?>
<ul>
<li>
    <img src="http://profile.ak.fbcdn.net/hprofile-ak-ash1/t5/373049_45576747489_456721932_q.jpg" class="avatar">
    <div class="status">
        <h2><a href="http://www.facebook.com/profile.php?id=45576747489" target="_blank">Smashing Magazine</a></h2>
        <p class="message">A couple of very inspiring videos to become a better designer, and a better person in general. <a href="http://aenism.com/inspiring-videos/" target="_blank">http://aenism.com/inspiring-videos/</a></p>
        <div class="attachment">
            <div class="attachment-data">
                <p class="name"><a href="http://aenism.com/inspiring-videos/" target="_blank">Inspiring videos – Aenism</a></p>
                <p class="caption">aenism.com</p>
                <p class="description">That made me a better designer.</p>
            </div>
        </div>
    </div>
    <p class="meta">12 hours ago ·       Comment   ·       Like    </p>
</li>
<li>
    <img src="http://profile.ak.fbcdn.net/hprofile-ak-ash1/t5/373049_45576747489_456721932_q.jpg" class="avatar">
    <div class="status">
        <h2><a href="http://www.facebook.com/profile.php?id=45576747489" target="_blank">Smashing Magazine</a></h2>
        <p class="message">Sub-sub-category links are important in eCommerce. Unfortunately, they are often ignored: <a href="http://baymard.com/blog/sub-sub-categories" target="_blank">http://baymard.com/blog/sub-sub-categories</a></p>
        <div class="attachment">
            <img class="picture" src="http://external.ak.fbcdn.net/safe_image.php?d=AQCYjgWyU4equdsK&amp;w=154&amp;h=154&amp;url=http%3A%2F%2Fassets.baymard.com%2Fblog%2Fsub-sub-categories-03-ikea-a-7c65aacddab042e3648334d8d642e557.jpg">
            <div class="attachment-data">
                <p class="name"><a href="http://baymard.com/blog/sub-sub-categories" target="_blank">Sub-Sub-Category Links: a Vital Feature in E-Commerce Navigation (50% Get it Wrong)</a></p>
                <p class="caption">baymard.com</p>
                <p class="description">This is the 7th in a series of 8 articles on product finding that draw on findings from our recent homepage and category usability report and benchmark.</p>
            </div>
        </div>
    </div>
    <p class="meta">14 hours ago ·      0 Comments   ·       Like    </p>
</li>
<li>
    <img src="http://profile.ak.fbcdn.net/hprofile-ak-ash1/t5/373049_45576747489_456721932_q.jpg" class="avatar">
    <div class="status">
        <h2><a href="http://www.facebook.com/profile.php?id=45576747489" target="_blank">Smashing Magazine</a></h2>
        <p class="message">A nice decent collection of less commonly used UNIX commands: <a href="http://www.danielmiessler.com/blog/collection-of-less-commonly-used-unix-commands" target="_blank">http://www.danielmiessler.com/blog/collection-of-less-commonly-used-unix-commands</a></p>
        <div class="attachment">
            <img class="picture" src="http://external.ak.fbcdn.net/safe_image.php?d=AQCpkDZ-PNuoQ69b&amp;w=154&amp;h=154&amp;url=http%3A%2F%2Fdanielmiessler.com%2Fblog%2Fwp-content%2Fuploads%2Funixcommands.png">
            <div class="attachment-data">
                <p class="name"><a href="http://www.danielmiessler.com/blog/collection-of-less-commonly-used-unix-commands" target="_blank">Collection of Less Commonly Used UNIX Commands - danielmiessler.com</a></p>
                <p class="caption">www.danielmiessler.com</p>
                <p class="description">A collection of the powerful UNIX and Linux commands that are seldom used.</p>
            </div>
        </div>
    </div>
    <p class="meta">15 hours ago ·       Comment   ·       Like    </p>
</li>
<li>
    <img src="http://profile.ak.fbcdn.net/hprofile-ak-ash1/t5/373049_45576747489_456721932_q.jpg" class="avatar">
    <div class="status">
        <h2><a href="http://www.facebook.com/profile.php?id=45576747489" target="_blank">Smashing Magazine</a></h2>
        <p class="message">Not quite sure why, but the interaction on Select Switch looks interesting. Any use cases where it would make sense? <a href="http://mnmly.github.io/select-switch/" target="_blank">http://mnmly.github.io/select-switch/</a></p>
    </div>
    <p class="meta">18 hours ago ·       Comment   ·       Like    </p>
</li>
<li>
    <img src="http://profile.ak.fbcdn.net/hprofile-ak-ash1/t5/373049_45576747489_456721932_q.jpg" class="avatar">
    <div class="status">
        <h2><a href="http://www.facebook.com/profile.php?id=45576747489" target="_blank">Smashing Magazine</a></h2>
        <p class="message">Do you use social login buttons (sign in with Facebook/Twitter) in your Web apps or online shops? Found lots of mixed opinions on the Web. Did they improve conversion rates in your case? Also, have you noticed any issues they introduced? See Mailchimp case-study: <a href="https://blog.mailchimp.com/social-login-buttons-arent-worth-it/" target="_blank">https://blog.mailchimp.com/social-login-buttons-arent-worth-it/</a></p>
    </div>
    <p class="meta">19 hours ago ·       Comment   ·       Like    </p>
</li>
<li>
    <img src="http://profile.ak.fbcdn.net/hprofile-ak-ash1/t5/373049_45576747489_456721932_q.jpg" class="avatar">
    <div class="status">
        <h2><a href="http://www.facebook.com/profile.php?id=45576747489" target="_blank">Smashing Magazine</a></h2>
        <p class="message">Why would even a professional designer or most experienced front-end Web developer use a popular responsive design framework such as Bootstrap or Foundation?
            Figure it out in today's article on Smashing Magazine: <a href="http://mobile.smashingmagazine.com/2014/02/19/responsive-design-frameworks-just-because-you-can-should-you/" target="_blank">http://mobile.smashingmagazine.com/2014/02/19/responsive-design-frameworks-just-because-you-can-should-you/</a>
        </p>
        <div class="attachment">
            <img class="picture" src="http://external.ak.fbcdn.net/safe_image.php?d=AQBXVFtoXxv1U4Zi&amp;w=154&amp;h=154&amp;url=https%3A%2F%2Ffbcdn-sphotos-d-a.akamaihd.net%2Fhphotos-ak-prn1%2Ft1%2F1970448_10152246079532490_977272267_n.png">
            <div class="attachment-data">
                <p class="name"><a href="http://mobile.smashingmagazine.com/2014/02/19/responsive-design-frameworks-just-because-you-can-should-you/" target="_blank">"Responsive Design Frameworks: Just Because You Can, Should You?" on Smashing Magazine</a></p>
                <p class="caption">mobile.smashingmagazine.com</p>
                <p class="description">The positive aspects of responsive design frameworks.</p>
            </div>
        </div>
    </div>
    <p class="meta">19 hours ago ·       Comment   ·       Like    </p>
</li>
<li>
    <img src="http://profile.ak.fbcdn.net/hprofile-ak-ash1/t5/373049_45576747489_456721932_q.jpg" class="avatar">
    <div class="status">
        <h2><a href="http://www.facebook.com/profile.php?id=45576747489" target="_blank">Smashing Magazine</a></h2>
        <p class="message">Brilliant: lots of practical, hands-on techniques available in SassConf conference videos — for free. <a href="https://vimeo.com/sassconf" target="_blank">https://vimeo.com/sassconf</a></p>
        <div class="attachment">
            <img class="picture" src="http://external.ak.fbcdn.net/safe_image.php?d=AQAJVV9oDoWGHVPT&amp;w=154&amp;h=154&amp;url=http%3A%2F%2Fb.vimeocdn.com%2Fps%2F632%2F019%2F6320193_300.jpg">
            <div class="attachment-data">
                <p class="name"><a href="https://vimeo.com/sassconf" target="_blank">SassConf Videos</a></p>
                <p class="caption">vimeo.com</p>
                <p class="description">SassConf is a two day conference devoted to modern front-end development. Day one is filled with talks from big players in the Sass and Front-End communities and…</p>
            </div>
        </div>
    </div>
    <p class="meta">21 hours ago ·      0 Comments   ·       Like    </p>
</li>
<li>
    <img src="http://profile.ak.fbcdn.net/hprofile-ak-ash1/t5/373049_45576747489_456721932_q.jpg" class="avatar">
    <div class="status">
        <h2><a href="http://www.facebook.com/profile.php?id=45576747489" target="_blank">Smashing Magazine</a></h2>
        <p class="message">Assumptions are sneaky and dangerous, that's why citable case-studies are so important. And Zurb Quips so useful. <a href="http://zurb.com/quips" target="_blank">http://zurb.com/quips</a></p>
        <div class="attachment">
            <img class="picture" src="http://external.ak.fbcdn.net/safe_image.php?d=AQCKH-xUE718sIbb&amp;w=154&amp;h=154&amp;url=http%3A%2F%2Fzurb.com%2Fquips%2Fassets%2Femerging-markets-b518624a196981057f12d6a428c846a0.png">
            <div class="attachment-data">
                <p class="name"><a href="http://zurb.com/quips" target="_blank">Design Quips from ZURB</a></p>
                <p class="caption">zurb.com</p>
                <p class="description">Design Quips is a tool that allows designers to justify their design based on empirical evidence.</p>
            </div>
        </div>
    </div>
    <p class="meta">23 hours ago ·       Comment   ·       Like    </p>
</li>
<li>
    <img src="http://profile.ak.fbcdn.net/hprofile-ak-ash1/t5/373049_45576747489_456721932_q.jpg" class="avatar">
    <div class="status">
        <h2><a href="http://www.facebook.com/profile.php?id=45576747489" target="_blank">Smashing Magazine</a></h2>
        <p class="message">What’s your strategy for dealing with IE8 in RWD?
            1. Px as fallback for rem,
            2. Fixed-width layout,
            3. Don’t worry too much about pseudo-selectors.
            What about you?
        </p>
    </div>
    <p class="meta">1 day ago ·       Comment   ·       Like    </p>
</li>
<li>
    <img src="http://profile.ak.fbcdn.net/hprofile-ak-ash1/t5/373049_45576747489_456721932_q.jpg" class="avatar">
    <div class="status">
        <h2><a href="http://www.facebook.com/profile.php?id=45576747489" target="_blank">Smashing Magazine</a></h2>
        <p class="message">Useful, if you design in Photoshop a lot. Ink PS plugin documents your layers, from typography to shape sizes. <a href="http://ink.chrometaphore.com" target="_blank">http://ink.chrometaphore.com</a></p>
        <div class="attachment">
            <img class="picture" src="http://external.ak.fbcdn.net/safe_image.php?d=AQB7PTvVCQonXepg&amp;w=154&amp;h=154&amp;url=http%3A%2F%2Fink.chrometaphore.com%2Fassets%2Ffeatures_bottom.png">
            <div class="attachment-data">
                <p class="name"><a href="http://ink.chrometaphore.com/" target="_blank">Ink | Photoshop documentor plugin</a></p>
                <p class="caption">ink.chrometaphore.com</p>
                <p class="description">Ink is a photoshop documentor plugin made by chrometaphore.com</p>
            </div>
        </div>
    </div>
    <p class="meta">1 day ago ·       Comment   ·       Like    </p>
</li>
<li>
    <img src="http://profile.ak.fbcdn.net/hprofile-ak-ash1/t5/373049_45576747489_456721932_q.jpg" class="avatar">
    <div class="status">
        <h2><a href="http://www.facebook.com/profile.php?id=45576747489" target="_blank">Smashing Magazine</a></h2>
        <p class="message">Aaaaand sent out! Our new email newsletter issue with CSS/JavaScript technique, freebies and useful tips and tricks. <a href="http://www.smashingmagazine.com/smashing-newsletter-issue-103/" target="_blank">http://www.smashingmagazine.com/smashing-newsletter-issue-103/</a></p>
        <div class="attachment">
            <img class="picture" src="http://external.ak.fbcdn.net/safe_image.php?d=AQD5axUrIlMCkOLP&amp;w=154&amp;h=154&amp;url=http%3A%2F%2Fmedia.smashingmagazine.com%2Fwp-content%2Fuploads%2F2014%2F02%2Fwhat-to-wear-opt.png">
            <div class="attachment-data">
                <p class="name"><a href="http://www.smashingmagazine.com/smashing-newsletter-issue-103/" target="_blank">Smashing Newsletter: Issue #103 | Smashing Magazine</a></p>
                <p class="caption">www.smashingmagazine.com</p>
                <p class="description">Every second Thursday we send out the Smashing newsletter with useful tips, tricks and resources for designers and developers.</p>
            </div>
        </div>
    </div>
    <p class="meta">1 day ago ·       Comment   ·       Like    </p>
</li>
<li>
    <img src="http://profile.ak.fbcdn.net/hprofile-ak-ash1/t5/373049_45576747489_456721932_q.jpg" class="avatar">
    <div class="status">
        <h2><a href="http://www.facebook.com/profile.php?id=45576747489" target="_blank">Smashing Magazine</a></h2>
        <p class="message">Another great and useful case-study: How the Guardian successfully moved domain to www.theguardian.com. <a href="http://www.theguardian.com/info/developer-blog/2014/feb/18/how-the-guardian-successfully-moved-domain" target="_blank">http://www.theguardian.com/info/developer-blog/2014/feb/18/how-the-guardian-successfully-moved-domain</a></p>
        <div class="attachment">
            <img class="picture" src="http://external.ak.fbcdn.net/safe_image.php?d=AQCv5eWzi3vVFL5x&amp;w=154&amp;h=154&amp;url=http%3A%2F%2Fi.guim.co.uk%2Fsys-images%2FGuardian%2FPix%2Fpictures%2F2014%2F2%2F17%2F1392633454516%2F8c7e3268-298d-4dcd-baea-a0e99ecb17a6-300x180.jpeg%3Fwidth%3D300%26height%3D-%26quality%3D95">
            <div class="attachment-data">
                <p class="name"><a href="http://www.theguardian.com/" target="_blank">The Guardian</a></p>
                <p class="caption">www.theguardian.com</p>
                <p class="description">US president warns Ugundan counterpart Yoweri Museveni that enacting bill would complicate relations between their countries</p>
            </div>
        </div>
    </div>
    <p class="meta">1 day ago ·      0 Comments   ·       Like    </p>
</li>
<li>
    <img src="http://profile.ak.fbcdn.net/hprofile-ak-ash1/t5/373049_45576747489_456721932_q.jpg" class="avatar">
    <div class="status">
        <h2><a href="http://www.facebook.com/profile.php?id=45576747489" target="_blank">Smashing Magazine</a></h2>
        <p class="message">"Type design is equal parts suffering and euphoria. It is a walk along a winding road that goes on for many weeks and months before it’s done. A type design brief is like a charter path: It asks you questions, and the answers will guide you to where you want to be. [...]"
            Continue reading on Smashing Magazine: <a href="http://www.smashingmagazine.com/2014/02/18/a-type-design-brief-arabic-typography-calligraphy/" target="_blank">http://www.smashingmagazine.com/2014/02/18/a-type-design-brief-arabic-typography-calligraphy/</a>
        </p>
        <div class="attachment">
            <img class="picture" src="http://external.ak.fbcdn.net/safe_image.php?d=AQB_BSXft1Lchh03&amp;w=154&amp;h=154&amp;url=http%3A%2F%2Fmedia.smashingmagazine.com%2Fwp-content%2Fuploads%2F2014%2F02%2Fimage-7-500px.png">
            <div class="attachment-data">
                <p class="name"><a href="http://www.smashingmagazine.com/2014/02/18/a-type-design-brief-arabic-typography-calligraphy/" target="_blank">A Type Design Brief: What Is In It, And Why Does It Matter?</a></p>
                <p class="caption">www.smashingmagazine.com</p>
                <p class="description">A typeface is a group of symbols destined to be rendered as words. The purpose of all letters is to communicate a visual or linguistic message to you, the reader. Sometimes they tell a story in a novel, sometimes the news of the day. At times, they direct you on the highway, while other times they u...</p>
            </div>
        </div>
    </div>
    <p class="meta">1 day ago ·      0 Comments   ·       Like    </p>
</li>
<li>
    <img src="http://profile.ak.fbcdn.net/hprofile-ak-ash1/t5/373049_45576747489_456721932_q.jpg" class="avatar">
    <div class="status">
        <h2><a href="http://www.facebook.com/profile.php?id=45576747489" target="_blank">Smashing Magazine</a></h2>
        <p class="message">TLDR Legal, software licenses in plain English. <a href="https://tldrlegal.com/" target="_blank">https://tldrlegal.com/</a> (via @ljungmark)</p>
        <div class="attachment">
            <div class="attachment-data">
                <p class="name"><a href="https://tldrlegal.com/" target="_blank">TLDRLegal - Software Licenses Explained in Plain English</a></p>
                <p class="caption">tldrlegal.com</p>
                <p class="description">Lookup open source licenses summarized &amp; explained in plain English.</p>
            </div>
        </div>
    </div>
    <p class="meta">1 day ago ·       Comment   ·       Like    </p>
</li>
<li>
    <img src="http://profile.ak.fbcdn.net/hprofile-ak-ash1/t5/373049_45576747489_456721932_q.jpg" class="avatar">
    <div class="status">
        <h2><a href="http://www.facebook.com/profile.php?id=45576747489" target="_blank">Smashing Magazine</a></h2>
        <p class="message">If you need jQuery, you need jQuery Builder: lets you build a "custom" jQuery with just the modules that you need. <a href="http://projects.jga.me/jquery-builder/" target="_blank">http://projects.jga.me/jquery-builder/</a> </p>
        <div class="attachment">
            <div class="attachment-data">
                <p class="name"><a href="http://projects.jga.me/jquery-builder/" target="_blank">jQuery Builder</a></p>
                <p class="caption">projects.jga.me</p>
                <p class="description"></p>
            </div>
        </div>
    </div>
    <p class="meta">2 days ago ·       Comment   ·       Like    </p>
</li>
</ul>
</div>
</div>
