
<div class="sign-wrapper">
    <?php

    $form = $this->profile_form;

    $form->setAttributes(array(
        'method' => 'post',
        'action' => $this->Url('private_profile/p_child', array('action' => 'updateProfile'))
    ));
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formFileSessionProgress();
    ?>
    <?php echo $this->formLabel($form->get('first_name'));?>

    <div class="standard-field">

        <div class="tip-wrapper">
            <div class="signtip" data-target="first_name">

                <?php
                 echo $this->userFormErrors($form->get('first_name'))
                ?>

            </div>
        </div>
        <?php echo $this->formElement($form->get('first_name'));?>
    </div>
    <?php echo $this->formLabel($form->get('last_name'));?>

    <div class="standard-field">
        <div class="tip-wrapper">
            <div class="signtip" data-target="last_name">
                <?php
                echo $this->userFormErrors($form->get('last_name'));
                ?>
            </div>
        </div>
        <?php echo $this->formElement($form->get('last_name'));?>

    </div>
    <?php echo $this->formLabel($form->get('profile_picture'));?>
    <div class="standard-field">

        <div class="tip-wrapper">
            <div class="signtip" data-target="profile_picture">
                <?php
                echo $this->userFormErrors($form->get('profile_picture'));?>
            </div>
        </div>

        <?php echo $this->formElement($form->get('profile_picture'));?>

    </div>


    <?php if($this->tmp_file) {


        $url = $this->url('prof_asset/profile_img',$this->profileImgResolver()->get($this->tmp_file,$this->user_id)); ?>

     <img src="<?php echo $url?>" alt="Your profile image"/>

    <?php }?>



    <?php echo $this->formElement($form->get('edit_token'));?>

    <input type="submit" value="submit">

    <?php echo $this->form()->closeTag(); ?>

</div>



