<div class="sign-wrapper">

    <?php

    $form = $this->picture_form;

    $form->setAttributes(array(
        'method' => 'post',
        'action' => $this->Url('private_profile/p_child', array('action' => 'updatePicture'))
    ));
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formFileSessionProgress();
    ?>

    <label for="profile_picture">Your picture</label>
    <div class="standard-field">

        <?php if($this->ProfileImg()->has()) {?>

        <img src=<?php echo $this->url($this->ProfileImg()->getRoute(),$this->ProfileImg()->get()) ?>>


        <?php }?>

        <div class="tip-wrapper">
            <div class="signtip" data-target="profile_picture">
                <?php echo $this->userFormErrors($form->get('profile_picture'));?>
            </div>
        </div>

        <?php echo $this->formElement($form->get('profile_picture'));?>

    </div>


    <?php echo $this->formElement($form->get('edit_token'));?>

    <input type="submit" value="submit">

    <?php echo $this->form()->closeTag(); ?>

</div>