
<?php if($this->validation_messages){?>

<div class="alert alert-danger">
    <?php
    if(is_array($this->validation_messages))
    {
        echo($this->validation_messages[0]);

    }else{
        echo $this->validation_messages;
    }

    }?>
</div>
<div class="sign-wrapper">
<?php
    (isset($this->failed_form)) ? $form = $this->failed_form : $form = $this->renderForm()->sign();
    $form->setAttributes(array(
    'method' => 'post',
    'action' => $this->Url('index/index_child', array('action' => 'sign'))
    ));
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formElementErrors()
    ->setMessageCloseString('</div>')
->setMessageOpenFormat('<div%s>')
->setAttributes(array('class' => 'alert alert-danger'))
->render($form->get('email'));
// ->setAttributes(array('class' =>'alert alert-danger' ));
?>


<?php echo $this->formLabel($form->get('username'));?>

<div class="standard-field" data-target="username">

    <div class="signtip">
        <p>Good</p>
    </div>
    <?php echo $this->formElement($form->get('username'));?>

</div>


<?php echo $this->formLabel($form->get('email'));?>

<div class="standard-field" data-target="email">
    <div class="signtip">
        <p>Good</p>
    </div>
    <?php echo $this->formElement($form->get('email'));?>

</div>


<?php $this->formElementErrors($form->get('email'));?>

<?php echo $this->formLabel($form->get('password'));?>


<div class="standard-field" data-target="password">

    <?php echo $this->formElement($form->get('password'));?>

</div>



<?php echo $this->formLabel($form->get('remember_me'));?>

<?php echo $this->formElement($form->get('remember_me'));?>


<?php echo $this->formElement($form->get('sign_token'));?>

<input type="submit" value="submit">

<?php echo $this->form()->closeTag(); ?>


</div>








<script>
        var valForm = {
            username: function(element){
                var inputData = $(element).serialize();
                $.ajax({
                    data: inputData,
                    type: "POST",
                    url: "<?php echo $this->url('usr/usr_child', array('action' => 'chkUname'))?>",
                    dataType: "json",
                    cache: false
                })
                    .done(function(data) {
                        if(data[0] == 1){
                            alert("Ok!");
                        }else{
                            console.log(valForm.parseResponse(data));
                        }

                    });
            },
            email: function(element){
                var inputData = $(element).serialize();

                $.ajax({
                    data: inputData,
                    type: "POST",
                    url: "<?php echo $this->url('usr/usr_child', array('action' => 'chkEmail'))?>",
                    dataType: "json",
                    cache: false
                })
                    .done(function(data) {
                        console.log(data);
                    });
            },


            parseResponse: function(response){
                    var parsedSet = [];

                $.each(response, function(key,value){

                    parsedSet.push(value);
                });

            return parsedSet;
            }
        };
    $(document).ready(function(){
        var timer = null;
        $("#username").on("keyup",function(e){
            clearTimeout(timer);
            timer = setTimeout(function(){
                valForm.username("#username");
            },1200);
        });

        $("#email").on("keyup",function(e){
            clearTimeout(timer);
            timer = setTimeout(function(){
                signRequest();
            },1200);
        });
    });

    function signRequest(){
        var formData = $('#username').serialize();
        $.ajax({
            data: formData,
            type: "POST",
            url: "<?php echo $this->url('index/index_child', array('action' => 'apiSign'))?>",
            dataType: "json",
            cache: false
        })
            .done(function(data) {
            console.log(data);
        });
    }












</script>




