


<?php if($this->validation_messages){?>


    <div class="alert alert-danger">
        <?php echo $this->validation_messages[0]; ?>
    </div>

    <?php  }?>

<?php

$form = $this->renderForm('login');

$form->setAttributes(array(
    'method' => 'post',
    'action' => $this->Url('index/index_child', array('action' => 'login'))
));

$form->prepare();

echo $this->form()->openTag($form);

echo $this->formLabel($form->get('email'));
echo $this->formElement($form->get('email'));

echo $this->formLabel($form->get('password'));
echo $this->formElement($form->get('password'));



echo $this->formLabel($form->get('remember_me'));
echo $this->formElement($form->get('remember_me'));


echo $this->formElement($form->get('csrf'));
echo $this->formElement($form->get('submit'));


echo $this->form()->closeTag();
?>